### ISSUE TITLE
Add the `vue-storefront-api` cache support

### ISSUE THREAD

**Issue by pkarw** [ClickAndMortar/docker#5]
The `vue-storefront-api` SSR cache works exactly the same way as `vue-storefront`. The only difference is the naming strategy for cache keys `api` instead of `page`: https://github.com/DivanteLtd/vue-storefront-api/blob/875ed27ad949c7a5e6db90cc8700761e8602a636/src/api/catalog.js#L10

**Comment by michael-bouvy** [comment]
@pkarw is detecting `/api` within request URI sure enough to get `api` cache instead of `page`?

**Comment by pkarw** [comment]
@michael-bouvy yes it should be just fine, however the only thing that needs to be checked is the `cache-version` - it might be a need to expose this from vsf-api as well

By the way - can you maybe contribute this change with `cache-version.json` to the VSF core in order to make the installation of this proxy module easier?

**Comment by michael-bouvy** [comment]
> @michael-bouvy yes it should be just fine, however the only thing that needs to be checked is the cache-version - it might be a need to expose this from vsf-api as well

Indeed, will do.

> By the way - can you maybe contribute this change with cache-version.json to the VSF core in order to make the installation of this proxy module easier?

Sure

**Comment by michael-bouvy** [comment]
@pkarw how to get cache version from VSF API ?

**Comment by pkarw** [comment]
OK, I've checked it and: nevermind; API is not using versioning

**Comment by michael-bouvy** [comment]
So `data:api:$cacheUri` ?

**Comment by pkarw** [comment]
@michael-bouvy yes, correct

**Comment by michael-bouvy** [comment]
@pkarw see https://github.com/DivanteLtd/vue-storefront/pull/4078 and https://github.com/ClickAndMortar/docker/pull/6

**Comment by michael-bouvy** [comment]
(wrong target repo for VSF PR)

**Comment by michael-bouvy** [comment]
Merged
